# Serverpod Passwords Configuration Template
# COPY THIS FILE TO passwords.yaml AND NEVER COMMIT passwords.yaml TO GIT!

development:
  database: 'incident_pulse_password'
  redis: ''
  serviceSecret: 'incident_pulse_local_dev_secret_key_32bytes_long!'

production:
  database: 'REPLACE_IN_PRODUCTION'
  redis: ''
  serviceSecret: 'REPLACE_IN_PRODUCTION'
