name: incident_pulse_flutter
description: Cross-platform Flutter dashboard and realtime war room for IncidentPulse.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.3.0'

dependencies:
  flutter:
    sdk: flutter
  incident_pulse_client:
    path: ../incident_pulse_client
  serverpod_flutter: ^2.4.0
  serverpod_auth_shared_flutter: ^2.4.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
